[package]
name = "relay-struct"
version = "0.1.0"
edition = "2021"
license = "EUPL-1.2"

[dependencies]
# Ser/De
serde = { version = "1", features = ["derive"] }
serde_json = "1"

# Server
axum = "0.7.9"
tokio = "1"

# Utilities
log = "0.4.22"
thiserror = "2"
